### ISSUE TITLE
`RefTraversal` documentation on the `action_fn` function doesn't match implementation.

### ISSUE THREAD

**Issue by Nashenas88** [michaelsproul/rust_radix_trie#14]
The note for `action_fn` on line 78 of `rust_radix_trie/src/traversal.rs` says:

    #[doc = "Note: this function isn't called in a `RefTraversal`/`RefTraversalMut`."]
    #[allow(unused)]
    fn action_fn...

The usage of it on line 111:

    if_else!($with_action, Self::action_fn(trie, intermediate, bucket), intermediate)

And the definitions of the traversals on line 117:

    make_traversal_trait!(name: Traversal, trie_type: &Trie<K, V>, with_action: true, mutability: );
    make_traversal_trait!(name: RefTraversal, trie_type: &'a Trie<K, V>, with_action: true, mutability: );

    make_traversal_trait!(name: TraversalMut, trie_type: &mut Trie<K, V>, with_action: true, mutability: mut);
    make_traversal_trait!(name: RefTraversalMut, trie_type: &'a mut Trie<K, V>, with_action: false, mutability: mut);

The inconsistent part seems to be that `with_action` for `RefTraversal` is `true` instead of `false`.

**Comment by michaelsproul** [comment]
Oh yes! You're right! I worked out it was ok to have an action function with immutable references, just not mutable ones. I'll push a doc update at once!

Thanks for catching this!

Out of interest, are you implementing your own traversal or just browsing/looking to use the trie?

**Comment by Nashenas88** [comment]
I was just reading the code out of an interest in Rust. I've never used a trie before. It's probably the first time I've found a bug while reading a code base for the first time :smile:. The cost is very well written, and it was easy to follow. I'm not so sure I would have found it in the functional, non-trait version.

**Comment by michaelsproul** [comment]
Aw, thank you :smile: Very well written apart from the bugs, lol!
