### ISSUE TITLE
Get prefix of subtrie

### ISSUE THREAD

**Issue by vks** [michaelsproul/rust_radix_trie#34]
Is there some way to get the prefix of a subtrie and convert it back to the original data type?

**Comment by vks** [comment]
Converting back to the original data type is actually not always possible, because the prefix has 4-bit boundaries, while the original data type might have different ones.

**Comment by michaelsproul** [comment]
Yes, and even with a vector of bytes, reversing the serialisation might not always work (e.g. you could cut a string half way through a multi-byte Unicode char). We could still have a method returning a `Result<K, Error>`
