### ISSUE TITLE
Implement Clone for Trie

### ISSUE THREAD

**Issue by manifest** [michaelsproul/rust_radix_trie#49]
At the moment, `Trie` doesn't implement `Clone` trait. That makes it difficult to use within other structs.

```rust
the trait `std::clone::Clone` is not implemented for `radix_trie::Trie<std::string::String, std::string::String>`
```

**Comment by michaelsproul** [comment]
Good point! It should be possible `#[derive(Clone)]` on `Trie` and `TrieNode` if you'd like to give it a go :)
