### ISSUE TITLE
implement a method is_leaf(key) ?

### ISSUE THREAD

**Issue by allan-simon** [michaelsproul/rust_radix_trie#5]
still for my parsing tool, i need to know if the current string is a terminal one (i.e regardless of which character i add at the end , i'm sure i can't make any longer word) 
with sequence trie, i implemented it on my side simply by doing 

```rust 
fn is_unique_match(words: &SequenceTrie<u8, ()>, value: &String) -> bool {

    if words.get(value.as_ref()).is_none() {
        return false;
    }

    words.get_node(value.as_ref()).map_or(
        false,
        |node| {
            let mut values = node.values();
            // we discard current value
            let _ = values.next();
            // and we check if there's a second
            match values.next() {
                Some(_) => false,
                None => true
            }

        }
    )

```
I guess looking to the internal of Radix tree, it's actually simpler as it just need to check that all the children are None (or child count is 0) 

as it may be more specific, if you think it does not belong to the library i'm fine with it.

**Comment by michaelsproul** [comment]
I'm on it.

**Comment by allan-simon** [comment]
ok, i'm going to have lunch, but i already made that , i haven't check if it compiles /works 

```rust
    /// Check if the given key is a leaf of the trie (i.e it exists and does not have
    /// successors
    pub fn is_leaf(&self, key: K) -> bool {
        let key_fragments = NibbleVec::from_byte_vec(key.encode());
        match get_node(self, key_fragments) {
            None => false,
            Some(node) => node.child_count != 0
        }   
    }   
```

**Comment by allan-simon** [comment]
ok, i'm going to have lunch, but i already made that , i haven't check if it compiles /works 

```rust
    /// Check if the given key is a leaf of the trie (i.e it exists and does not have
    /// successors
    pub fn is_leaf(&self, key: K) -> bool {
        let key_fragments = NibbleVec::from_byte_vec(key.encode());
        match get_node(self, key_fragments) {
            None => false,
            Some(node) => node.child_count != 0
        }   
    }   
```

**Comment by michaelsproul** [comment]
Oh, interesting. My implementation was just:

```rust
fn is_leaf(&self) -> bool {
  self.child_count == 0
}
```

Then you can use it like:

```rust
trie.get_node(key).and_then(|node| node.is_leaf()); // Option<bool>

// Or with a default.
trie.get_node(key).and_then(|node| node.is_leaf()).or(false);
```

At the moment I prefer this API because it prevents double-lookups if you're already doing something with the node. I'm adding a few more functions in the same spirit - operating on nodes directly to enable more complex usage patterns.

**Comment by allan-simon** [comment]
yup you're right, your solution make it easier to compose with other function. I have to admit i made mind with only my specific problem in mind ^^'

**Comment by allan-simon** [comment]
now that I think about it, nothing prevent to have both, one for composability , and one for conveniency purpose is_key_leaf or something like that, but maybe it's just me who wants to have a readable code as a library user :P

**Comment by michaelsproul** [comment]
It seems like a very specific use-case is my only worry. Keeping the API simple is a virtue :stuck_out_tongue: I almost got rid of the method that returns an ancestor value, seeing as it's just:

```rust
trie.get_ancestor(key).and_then(|t| t.value())
```

**Comment by allan-simon** [comment]
sure, no problem, it was just me lobbying to make my own life easier ^^
