### ISSUE TITLE
Plagued by Bugs.

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/rust_radix_trie#8]
I've found 3 in the past day. Really needs QuickCheck tests.

**Comment by michaelsproul** [comment]
@allan-simon: This library is in worse shape than I thought, if you'd like to help clean it up that would be much appreciated. I'm not actually using this library for anything so at the moment it's feeling like a maintenance burden...

**Comment by allan-simon** [comment]
sure, if you can list those you have found for the moment, i can have a look at them

**Comment by michaelsproul** [comment]
I've fixed all the ones I've found (56a01a36c5c9b62770e4b39d445325265aefc582, 1e9f5e24aaf742ca762a98544264b1fcbb29e159, c82b81917dc07640ae68c2abf26f77e43d131d71), but I suspect there are more.

**Comment by allan-simon** [comment]
ok i see, i'm just missing the get_successor method you were talking last time in the other thread, and i should be ready to fully implement it in a real case, and starting from there i will take on fixing the bug i found (as i'm better at fixing code than creating new code) , deal ? :)

**Comment by michaelsproul** [comment]
yeah, I've just been wrestling with immutable/mutable traversals, which will make implementing `get_successor` easy (less code duplication).

**Comment by michaelsproul** [comment]
coming soon!

**Comment by allan-simon** [comment]
great to hear :)

**Comment by michaelsproul** [comment]
Ok @allan-simon, the `get_descendant` function is ready to roll.

**Comment by allan-simon** [comment]
thanks, works great, for the plagued by bugs, it seems to be acceptable, at least for my project, i haven't done precise comparison, but the results does not look weird to me, after i haven't made any big use of the iterators yet. 

I will see in the next days to reimplement one of my earlier webservice that was implemented in C, for an autocompletion webservice. for which it will make extensive use of iterators.

**Comment by michaelsproul** [comment]
Yeah, I suspect we might actually be free of bugs (for now), but I'm still keen to add a bunch of QuickCheck tests at some point.

**Comment by michaelsproul** [comment]
Let me know how your app goes, sounds awesome!

**Comment by allan-simon** [comment]
right now i'm making research on the 2 points that was a "blocker" on the c implementation , which were collation, i.e  being able to autocomplete "Immédiate"  when typing  "imme"  (i think rust already have some standard library functions for that ) , and lexical order being different from one language to an other (this one may be more of an headache, as it means you can't simply rely anymore on the byte representation of the string to make a numeric sort)

**Comment by michaelsproul** [comment]
Given that it's been half a year without bug reports... and the quickcheck tests exist now, I'm going to close this!
